version: 0.2

phases:
  install:
    commands:
      - echo Installing NPM dependencies...
      - cd frontend  # 切换到 frontend 目录
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build --prod
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist/frontend  # 指定构建产物目录
