name: Build and Deploy Angular App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'  # 使用最新的 Node.js 20

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build --prod

    - name: Upload production-ready build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: frontend/dist
